name: CI-Debug

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest] # [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/debug/"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/debug/short"

    steps:
    - uses: actions/checkout@v2

    # Check if GitHub Cache has it, because that's free
    - name: Using the builtin GitHub Cache Action for .conan
      if: matrix.os != 'windows-latest'
      id: github-cache-conan
      uses: actions/cache@v1
      env:
        cache-name: cache-conan-modules
      with:
        path: ${{ env.CONAN_USER_HOME }}
        key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-debug-${{ hashFiles('conanfile.py') }}

    # If GitHub Cache doesn't have it, get from Conan Cache (has git lfs cost)
    - name: Cache Conan modules
      if: steps.github-cache-conan.outputs.cache-hit != 'true'
      id: cache-conan
      uses: turtlebrowser/conan-cache@v1.1
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ matrix.os }}-debug-${{ hashFiles('conanfile.py') }}
          target_os: ${{ runner.os }}-${{ matrix.os }}-debug
          lfs_limit: 60

    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: echo "::add-path::/home/runner/.local/bin"

    - name: Remove all previous builds
      # Mac and not hit in either cache
      if: (matrix.os == 'macos-latest') && (steps.github-cache-conan.outputs.cache-hit != 'true') && (steps.cache-conan.outputs.cache-hit != 1)
      run: conan remove -f "*"

#    - name: Install patched conan-qt
#      run: |
#        git clone https://github.com/patricia-gallardo/conan-qt.git
#        cd conan-qt
#        git checkout get_opus_from_chromium
#        conan export . qt/5.15.0@patricia-gallardo/patched

    - name: Get Conan Dependencies
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: cmake --build build
