name: Update Languages

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 23 * * 2'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      CONAN_SYSREQUIRES_MODE: enabled
      INSTALL_DIR: ${{ github.workspace }}/install/

    steps:
    - uses: actions/checkout@v2

    - name: Cache Conan modules
      id: cache-conan
      uses: turtlebrowser/conan-cache@v1.1
      with:
          bot_name: turtlebrowser-bot
          bot_token: ${{ secrets.CACHE_REPO_TOKEN }}
          cache_name: turtlebrowser/conan-cache-turtlebrowser
          key: host-${{ runner.os }}-target-${{ runner.os }}-${{ hashFiles('conanfile.py') }}
          target_os: ${{ runner.os }}
          lfs_limit: 60

    - name: Get Conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        mkdir build
        
    - name: Fix Path on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: echo "::add-path::/home/runner/.local/bin"

    - name: Set up build for language files
      working-directory: build
      run: cmake -DENABLE_TS_RESCAN=ON -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }} -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      working-directory: build
      run: cmake --build . --config Release -j 4

#    - name: Install language files
#      working-directory: build
#      run: cmake --build . --config Release --target install
         
    - name: Configure Git
      shell: bash
      run: |
        git config user.email "bot@turtlebrowser.com"
        git config user.name "Turtle Bot (GitHub Action)"
        git config core.longpaths true
        git config pull.rebase true
        git config rebase.autoStash true
        git pull
        
    - name: Commit language files
      shell: bash
      working-directory: src
      run: | 
        if [[ "$( git status --porcelain *.ts)" != "" ]]; then
          git add -A *.ts
          git commit -m "Updated language files"
        fi
              
    - name: Push language files
      shell: bash
      run: |
        git pull
        git push
        
    - name: Prepare test build
      run: |
        git checkout .
        git clean -dfx
        mkdir build
 
    - name: Perfom test build
      working-directory: build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . --config Release -j 4
